#!/usr/bin/env python3
"""
AI Engine GEMM Output Comparison Script
======================================

This script provides comprehensive comparison functionality between AI Engine GEMM
simulator output and golden reference files. It supports all data types, matrix
dimensions, and configuration parameters used in the AI Engine GEMM application.

Key Features:
- Automatic configuration reading from config.json
- Support for all data types (int16, int32, float, bfloat16, int8, int4)
- Tolerance-based comparison for floating-point data
- Exact comparison for integer data types
- When SIMPLE_OUT_C=1: design/aie_src/c.txt vs aiesim_data/gemm_*_ioFiles/c_golden.txt. When 0: design/aie_src/c.txt vs aiesim_data/gemm_*_ioFiles/matrix_C_golden.txt
- Detailed difference reporting with statistics
- Comprehensive error handling and validation

Architecture:
- Configuration Management: Reads all parameters from centralized config.json
- Matrix Loading: Handles different data types with appropriate numpy dtypes
- Comparison Engine: Implements tolerance-based and exact comparison methods
- Reporting System: Provides detailed statistics and difference analysis

Usage:
    python compare_outputs.py

Prerequisites:
- config.json file in design/design_configs/ directory
- Golden reference files generated by plioGen.py
- Simulator output file (c.txt)

Output Files Expected:
- c.txt: design/aie_src/c.txt (or aiesim_data/, then build paths). Used for both modes.
- When SIMPLE_OUT_C=1: golden = aiesim_data/gemm_*_ioFiles/c_golden.txt (buffer order, word-per-line).
- When SIMPLE_OUT_C=0: golden = aiesim_data/gemm_*_ioFiles/matrix_C_golden.txt (raw row-major).

Return Codes:
- 0: Comparison passed (c.txt matches c_golden.txt or matrix_C_golden.txt per SIMPLE_OUT_C)
- 1: Comparison failed or files missing

Author: Advanced Micro Devices, Inc.
Copyright (C) 2024, Advanced Micro Devices, Inc. All rights reserved.
SPDX-License-Identifier: MIT
"""

import os
import sys
import numpy as np
import json

def read_all_parameters_from_config(config_file_path):
    """
    Read all parameters from config.json file.
    
    This function loads the centralized configuration file and extracts all
    necessary parameters for the AI Engine GEMM application. It provides
    default values for all parameters to ensure robust operation even if
    the configuration file is missing or incomplete.
    
    Args:
        config_file_path (str): Path to the config.json file
        
    Returns:
        dict: Dictionary containing all configuration parameters with the following keys:
            - GEMM_SIZE_A, GEMM_SIZE_AB, GEMM_SIZE_B (int): Matrix dimensions (REQUIRED - must be provided in config.json)
            - DIM (int): Tile dimension (default: 8)
            - SPLIT (int): Number of AI Engine splits (default: 2)
            - CASC_LN (int): Number of cascade levels (default: 8)
            - DATA_TYPE (str): Data type (default: 'int16')
            - TARGET_HW_EMU (int): Hardware emulation target flag (default: 1)
            - ITER_CNT (int): Iteration count (default: -1)
            - N_SAMPLES (int): Number of samples (default: 1)
            - GEMM_INSTS (int): Number of GEMM instances (default: 1)
            - EN_TRACE (int): Enable tracing flag (default: 0)
    
    Raises:
        FileNotFoundError: If config file doesn't exist (handled gracefully)
        Exception: If JSON parsing fails (handled gracefully)
    """
    # Initialize default values
    params = {
        'DIM': 16,
        'DIM_A': 16,
        'DIM_AB': 4,
        'DIM_B': 16,
        'SPLIT': 2,
        'CASC_LN': 8,
        'DATA_TYPE': 'int16',
        'TARGET_HW_EMU': 0,
        'ITER_CNT': 1,
        'N_SAMPLES': 1,
        'GEMM_INSTS': 1,
        'EN_TRACE': 0,
        'TILE_MEM_BYTES': 32768,
        'PL_FREQ': 312.5,
        'ENABLE_ML_BENCHMARKS': 0,
        'TARGET': 'hw'
    }
    
    try:
        with open(config_file_path, 'r') as f:
            config_data = json.load(f)
        
        # Map JSON keys to our parameter names (only user-specified parameters)
        # Read GEMM_SIZE_A, AB, B (required - no fallback to GEMM_SIZE)
        if 'GEMM_SIZE_A' in config_data:
            params['GEMM_SIZE_A'] = int(config_data['GEMM_SIZE_A'])
        if 'GEMM_SIZE_AB' in config_data:
            params['GEMM_SIZE_AB'] = int(config_data['GEMM_SIZE_AB'])
        if 'GEMM_SIZE_B' in config_data:
            params['GEMM_SIZE_B'] = int(config_data['GEMM_SIZE_B'])
        if 'DIM' in config_data:
            params['DIM'] = int(config_data['DIM'])
        
        # Read new parameter names (with backward compatibility) FIRST, before calculating DIM_A/AB/B
        if 'SPLIT_A' in config_data:
            params['SPLIT_A'] = int(config_data['SPLIT_A'])
        elif 'SPLIT' in config_data:
            params['SPLIT_A'] = int(config_data['SPLIT'])
        
        if 'SPLIT_B' in config_data:
            params['SPLIT_B'] = int(config_data['SPLIT_B'])
        elif 'SPLIT' in config_data:
            params['SPLIT_B'] = int(config_data['SPLIT'])
        
        if 'CASC_LN_AB' in config_data:
            params['CASC_LN_AB'] = int(config_data['CASC_LN_AB'])
        elif 'CASC_LN' in config_data:
            params['CASC_LN_AB'] = int(config_data['CASC_LN'])
        
        # For backward compatibility, also set SPLIT and CASC_LN
        if 'SPLIT' not in params:
            params['SPLIT'] = params.get('SPLIT_B', 2)
        if 'CASC_LN' not in params:
            params['CASC_LN'] = params.get('CASC_LN_AB', 8)
        
        # Calculate DIM_A, DIM_B as min(DIM, ...); DIM_AB is always GEMM_SIZE_AB // CASC_LN_AB
        # NOTE: This must happen AFTER reading SPLIT_A/B and CASC_LN_AB from config
        if 'DIM' in params:
            dim_base = params['DIM']
            # DIM_A = min(DIM, GEMM_SIZE_A / SPLIT_A)
            if 'GEMM_SIZE_A' in params and 'SPLIT_A' in params:
                params['DIM_A'] = min(dim_base, params['GEMM_SIZE_A'] // max(1, params['SPLIT_A']))
            elif 'GEMM_SIZE_A' in params and 'SPLIT' in params:
                params['DIM_A'] = min(dim_base, params['GEMM_SIZE_A'] // max(1, params['SPLIT']))
            else:
                params['DIM_A'] = dim_base
            # DIM_AB is always GEMM_SIZE_AB // CASC_LN_AB
            if 'GEMM_SIZE_AB' in params and 'CASC_LN_AB' in params:
                params['DIM_AB'] = params['GEMM_SIZE_AB'] // max(1, params['CASC_LN_AB'])
            elif 'GEMM_SIZE_AB' in params and 'CASC_LN' in params:
                params['DIM_AB'] = params['GEMM_SIZE_AB'] // max(1, params['CASC_LN'])
            else:
                params['DIM_AB'] = params.get('GEMM_SIZE_AB', 64) // max(1, params.get('CASC_LN_AB', params.get('CASC_LN', 8)))
            # DIM_B = min(DIM, GEMM_SIZE_B / SPLIT_B)
            if 'GEMM_SIZE_B' in params and 'SPLIT_B' in params:
                params['DIM_B'] = min(dim_base, params['GEMM_SIZE_B'] // max(1, params['SPLIT_B']))
            elif 'GEMM_SIZE_B' in params and 'SPLIT' in params:
                params['DIM_B'] = min(dim_base, params['GEMM_SIZE_B'] // max(1, params['SPLIT']))
            else:
                params['DIM_B'] = dim_base
        if 'ITER_CNT' in config_data:
            params['ITER_CNT'] = int(config_data['ITER_CNT'])
        if 'N_SAMPLES' in config_data:
            params['N_SAMPLES'] = int(config_data['N_SAMPLES'])
        if 'GEMM_INSTS' in config_data:
            params['GEMM_INSTS'] = int(config_data['GEMM_INSTS'])
        if 'EN_TRACE' in config_data:
            params['EN_TRACE'] = int(config_data['EN_TRACE'])
        if 'DATA_TYPE' in config_data:
            params['DATA_TYPE'] = str(config_data['DATA_TYPE'])
        
        # Set TARGET and TARGET_HW_EMU based on TARGET field
        if 'TARGET' in config_data:
            params['TARGET'] = config_data['TARGET']
            target = str(config_data['TARGET']).lower()
            if target == 'hw_emu':
                params['TARGET_HW_EMU'] = 1
            else:
                params['TARGET_HW_EMU'] = 0
        
        # Set additional parameters from config
        if 'TILE_MEM_BYTES' in config_data:
            params['TILE_MEM_BYTES'] = int(config_data['TILE_MEM_BYTES'])
        if 'PL_FREQ' in config_data:
            params['PL_FREQ'] = float(config_data['PL_FREQ'])
        if 'ENABLE_ML_BENCHMARKS' in config_data:
            params['ENABLE_ML_BENCHMARKS'] = int(config_data['ENABLE_ML_BENCHMARKS'])

        print(f"Successfully read parameters from config file:")
        for key, value in params.items():
            print(f"  {key}: {value}")
        
        return params
        
    except FileNotFoundError:
        print(f"Warning: Config file not found: {config_file_path}, using defaults")
        return params
    except Exception as e:
        print(f"Error reading config file: {e}, using defaults")
        return params

def get_word_length(data_type="int16"):
    """
    Calculate the word length (WRD_LN) based on data type.
    
    Word length represents the number of data elements that fit in a 128-bit PLIO transfer.
    This is crucial for understanding how data is packed and transferred between the
    Programmable Logic and AI Engine via PLIO interfaces.
    
    Args:
        data_type (str): Data type string (e.g., 'int16', 'int32', 'float', 'bfloat16')
        
    Returns:
        int: Number of elements that fit in a 128-bit transfer
        
    Supported Data Types:
        - int4/uint4: 32 elements per 128-bit transfer (4 bits per element)
        - int8/uint8: 16 elements per 128-bit transfer (8 bits per element)
        - int16/uint16/bfloat16: 8 elements per 128-bit transfer (16 bits per element)
        - int32/uint32/float: 4 elements per 128-bit transfer (32 bits per element)
        - Default: 8 elements per 128-bit transfer (for unsupported types)
    """
    if data_type in ["int4", "uint4"]:
        return 32
    elif data_type in ["int8", "uint8"]:
        return 16
    elif data_type in ["int16", "uint16", "bfloat16"]:
        return 8
    elif data_type in ["int32", "uint32", "float"]:
        return 4
    else:
        return 8


def find_first_existing_file(candidate_paths):
    """
    Return the first existing path from a list, else None.
    """
    for p in candidate_paths:
        if p and os.path.exists(p):
            return p
    return None


def build_output_search_dirs(build_base, size_part, target):
    """
    Return a prioritized list of directories where outputs may be located.

    Prefer c.txt from design/aie_src/ (used for both SIMPLE_OUT_C=0 and SIMPLE_OUT_C=1).
    Then design/aie_src/aiesim_data/, then build/package paths.
    """
    script_dir = os.path.dirname(os.path.abspath(__file__))
    aie_src_dir = os.path.dirname(script_dir)  # design/aie_src/
    dirs = [
        aie_src_dir,   # design/aie_src/ — c.txt (board/sim) for both SIMPLE_OUT_C=0 and 1
        script_dir,     # design/aie_src/aiesim_data/
    ]
    # Build folders as fallback only when c.txt is not in aiesim_data
    if size_part:
        dirs.append(os.path.join(build_base, f'gemm_{size_part}', 'x1', target, 'aiesimulator_output', 'data'))
        dirs.append(os.path.join(build_base, f'gemm_{size_part}', 'x1', target, 'package', 'sd_card', 'output_files'))
        dirs.append(os.path.join(build_base, f'gemm_{size_part}', 'x1', target, 'package', 'sd_card'))
    return dirs


def load_matrix_from_file(filepath, data_type="int16"):
    """
    Load matrix from file with appropriate data type handling.
    
    This function loads matrix data from text files and converts it to the
    appropriate numpy data type based on the specified data type. It handles
    all supported data types used in the AI Engine GEMM application.
    
    Args:
        filepath (str): Path to the matrix file
        data_type (str): Data type string (e.g., 'int16', 'int32', 'float', 'bfloat16')
        
    Returns:
        numpy.ndarray or None: Loaded matrix with appropriate data type, or None if loading fails
        
    Supported Data Types:
        - bfloat16: Loaded as float32 (numpy doesn't have native bfloat16)
        - float: Loaded as float32
        - int16/uint16: Loaded as int16
        - int32/uint32: Loaded as int32
        - int8/uint8: Loaded as int8
        - int4/uint4: Loaded as int8 (int4 stored as int8)
        - Default: int16
        
    Note:
        - Automatically filters out timestamp lines (lines starting with 'T')
        - Handles simulator output format which includes timing information
        
    Raises:
        Exception: If file loading fails (handled gracefully, returns None)
    """
    try:
        # Read file and filter out timestamp lines (lines starting with 'T')
        with open(filepath, 'r') as f:
            lines = []
            for line in f:
                line = line.strip()
                # Skip empty lines and timestamp lines (starting with 'T')
                if line and not line.startswith('T'):
                    lines.append(line)
        
        if not lines:
            print(f"Warning: No data lines found in {filepath} (only timestamps or empty lines)")
            return None
        
        # Create a temporary string buffer with just the data lines
        from io import StringIO
        data_content = '\n'.join(lines)
        
        if data_type == "bfloat16":
            matrix = np.loadtxt(StringIO(data_content), dtype=np.float32)
        elif data_type == "float":
            matrix = np.loadtxt(StringIO(data_content), dtype=np.float32)
        elif data_type in ["int16", "uint16"]:
            matrix = np.loadtxt(StringIO(data_content), dtype=np.int16)
        elif data_type in ["int32", "uint32"]:
            matrix = np.loadtxt(StringIO(data_content), dtype=np.int32)
        elif data_type in ["int8", "uint8"]:
            matrix = np.loadtxt(StringIO(data_content), dtype=np.int8)
        elif data_type in ["int4", "uint4"]:
            matrix = np.loadtxt(StringIO(data_content), dtype=np.int8)  # int4 stored as int8
        else:
            # Default to int16
            matrix = np.loadtxt(StringIO(data_content), dtype=np.int16)
        return matrix
    except Exception as e:
        print(f"Error loading matrix from {filepath}: {e}")
        return None

def compare_matrices(golden_matrix, output_matrix, matrix_name):
    """
    Compare two matrices and report differences with tolerance for float precision.
    
    This function performs intelligent comparison between golden reference and
    generated output matrices. It uses different comparison strategies based on
    the data type: exact comparison for integer types and tolerance-based
    comparison for floating-point types.
    
    Args:
        golden_matrix (numpy.ndarray): Golden reference matrix
        output_matrix (numpy.ndarray): Generated output matrix
        matrix_name (str): Name of the matrix for reporting purposes
        
    Returns:
        bool: True if matrices match (within tolerance), False otherwise
        
    Comparison Strategy:
        - Integer types (int8, int16, int32, uint8, uint16, uint32, int4, uint4):
          Exact comparison with zero tolerance
        - Floating-point types (float, bfloat16):
          Tolerance-based comparison with 1e-4 absolute tolerance
          Data is rounded to 4 decimal places before comparison
          
    Reporting Features:
        - Shape validation and mismatch reporting
        - Detailed statistics (max diff, mean diff, match percentage)
        - First 10 differences shown with positions and values
        - Comprehensive error reporting for debugging
    """
    if golden_matrix.shape != output_matrix.shape:
        print(f"Shape mismatch for {matrix_name}:")
        print(f"  Golden shape: {golden_matrix.shape}")
        print(f"  Output shape: {output_matrix.shape}")
        return False
    
    # Use tolerance-based comparison for float data
    if golden_matrix.dtype in [np.float32, np.float64]:
        # Round to 0 decimal places for comparison (whole numbers only)
        golden_rounded = np.round(golden_matrix, 0)
        output_rounded = np.round(output_matrix, 0)
        
        # Use numpy's allclose with tolerance
        tolerance = 1e0  # 1.0
        is_close = np.allclose(golden_rounded, output_rounded, atol=tolerance, rtol=0)
        
        if is_close:
            print(f"[OK] {matrix_name}: Match within tolerance (whole numbers only, ignoring all decimal digits)")
            return True
        else:
            # Calculate differences on rounded data
            diff_matrix = np.abs(golden_rounded - output_rounded)
            max_diff = np.max(diff_matrix)
            mean_diff = np.mean(diff_matrix)
            num_differences = np.count_nonzero(diff_matrix)
            total_elements = golden_matrix.size
            match_percentage = ((total_elements - num_differences) / total_elements) * 100
            
            print(f"[FAIL] {matrix_name}: Found {num_differences} differences after rounding to whole numbers")
            print(f"  Maximum absolute difference: {max_diff}")
            print(f"  Mean absolute difference: {mean_diff:.4f}")
            print(f"  Percentage of matching elements: {match_percentage:.2f}%")
            
            # Show first few differences
            diff_positions = np.where(diff_matrix > 0)
            num_to_show = min(10, num_differences)
            
            print(f"  First {num_to_show} differences:")
            for i in range(num_to_show):
                row, col = diff_positions[0][i], diff_positions[1][i]
                golden_val = golden_matrix[row, col]
                output_val = output_matrix[row, col]
                golden_rounded_val = golden_rounded[row, col]
                output_rounded_val = output_rounded[row, col]
                print(f"    Position [{row:3d},{col:3d}]: Golden={golden_val:.4f} -> {golden_rounded_val:.1f}, Output={output_val:.4f} -> {output_rounded_val:.1f}, Diff={diff_matrix[row, col]:.1f}")
    else:
        # Exact comparison for integer data
        diff_matrix = np.abs(golden_matrix - output_matrix)
        max_diff = np.max(diff_matrix)
        mean_diff = np.mean(diff_matrix)
        num_differences = np.count_nonzero(diff_matrix)
        total_elements = golden_matrix.size
        match_percentage = ((total_elements - num_differences) / total_elements) * 100
        
        if num_differences == 0:
            print(f"[OK] {matrix_name}: Perfect match (100% identical)")
            return True
        else:
            print(f"[FAIL] {matrix_name}: Found {num_differences} differences")
            print(f"  Maximum absolute difference: {max_diff}")
            print(f"  Mean absolute difference: {mean_diff:.4f}")
            print(f"  Percentage of matching elements: {match_percentage:.2f}%")
        
        # Show first few differences
        diff_positions = np.where(diff_matrix > 0)
        num_to_show = min(10, num_differences)
        
        print(f"  First {num_to_show} differences:")
        for i in range(num_to_show):
            row, col = diff_positions[0][i], diff_positions[1][i]
            golden_val = golden_matrix[row, col]
            output_val = output_matrix[row, col]
            print(f"    [{row}, {col}]: Golden={golden_val}, Output={output_val}")
        
        if num_differences > 10:
            print(f"  ... and {num_differences - 10} more differences")
        
        return False

def run_comparison(directory, data_type="int16", gemm_size=32):
    """
    Run comparison between golden file and generated output.

    Compares c.txt (simulator/output) with matrix_C_golden.txt (golden reference).
    Both files are raw row-major format: GEMM_SIZE_A rows × GEMM_SIZE_B columns.

    Args:
        directory (str): Directory containing matrix_C_golden.txt
        data_type (str): Data type for matrix loading (default: "int16")
        gemm_size (int): GEMM matrix size for directory naming (default: 32)

    Returns:
        bool: True if comparison passes, False otherwise.
    """
    print(f"\nStarting comparison in directory: {directory}")
    print(f"Data type: {data_type}")

    # Resolve paths: c.txt from design/aie_src/ (or aiesim_data/); golden from directory (gemm_*_ioFiles/)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(script_dir, '..', '..', '..'))
    build_base = os.path.join(project_root, 'build')
    config_file_path = os.path.join(project_root, 'design', 'design_configs', 'config.json')
    target = 'hw'  # Default to 'hw'
    if os.path.exists(config_file_path):
        try:
            import json
            with open(config_file_path, 'r') as f:
                config_data = json.load(f)
                if 'TARGET' in config_data:
                    target = str(config_data['TARGET']).lower()
        except Exception:
            pass  # Use default 'hw' if config read fails
    
    # Extract size from directory name (e.g., gemm_2048x64x8_ioFiles -> 2048x64x8)
    dir_name = os.path.basename(directory)
    size_part = None
    if dir_name.startswith('gemm_') and dir_name.endswith('_ioFiles'):
        size_part = dir_name[5:-8]  # Remove 'gemm_' prefix and '_ioFiles' suffix

    # Output discovery for c.txt
    search_dirs = build_output_search_dirs(build_base, size_part, target)
    
    print("\nOutput search directories (in priority order):")
    for d in search_dirs:
        print(f"  - {d}")

    generated_output_path = find_first_existing_file([os.path.join(d, "c.txt") for d in search_dirs])
    if generated_output_path is None:
        generated_output_path = "c.txt"  # keep message consistent below

    # SIMPLE_OUT_C from config: 1 (or true) = simple out_C -> c.txt vs c_golden.txt; 0 = complex -> c.txt vs matrix_C_golden.txt
    simple_out_c = True
    if os.path.exists(config_file_path):
        try:
            with open(config_file_path, 'r') as f:
                cfg = json.load(f)
            simple_out_c = bool(cfg.get('SIMPLE_OUT_C', 1))
        except Exception:
            pass
    # directory = aiesim_data/gemm_*_ioFiles/ (e.g. gemm_32x64x32_ioFiles)
    c_golden_path = os.path.join(directory, "c_golden.txt")
    matrix_c_golden_path = os.path.join(directory, "matrix_C_golden.txt")
    use_c_golden = simple_out_c
    # SIMPLE_OUT_C=1: c.txt (aie_src/) vs c_golden.txt; SIMPLE_OUT_C=0: c.txt (aie_src/) vs matrix_C_golden.txt
    golden_path = c_golden_path if use_c_golden else matrix_c_golden_path

    print(f"\n{'='*80}")
    print(f"COMPARISON: c.txt vs {'c_golden.txt' if use_c_golden else 'matrix_C_golden.txt'} (SIMPLE_OUT_C={int(simple_out_c)} from config)")
    print(f"{'='*80}")

    if os.path.exists(golden_path) and os.path.exists(generated_output_path):
        print(f"  Golden:   {golden_path}" + (" (buffer order, word-per-line)" if use_c_golden else " (raw row-major)"))
        print(f"  Output:   {generated_output_path}")

        golden_matrix = load_matrix_from_file(golden_path, data_type)
        output_matrix = load_matrix_from_file(generated_output_path, data_type)

        result = False
        if use_c_golden:
            # c.txt and c_golden.txt same format: one line per word, WRD_LN elements per line; compare directly
            if golden_matrix is not None and output_matrix is not None:
                if golden_matrix.shape != output_matrix.shape:
                    print(f"\n[FAIL] Shape mismatch: c_golden.txt {golden_matrix.shape} vs c.txt {output_matrix.shape}")
                else:
                    result = compare_matrices(golden_matrix, output_matrix, "C (c.txt vs c_golden.txt)")
                if result:
                    print(f"\n[OK] c.txt matches c_golden.txt")
                else:
                    print(f"\n[FAIL] c.txt does not match c_golden.txt")
                    try:
                        print(f"\n  Golden line 0 (first 8): {golden_matrix[0].tolist()}")
                        print(f"  Output line 0 (first 8):  {output_matrix[0].tolist()}")
                    except Exception:
                        pass
                    print(f"\n  If inp_A converts matrix_A_input.txt correctly to a0_casc*, c.txt should match c_golden.txt.")
            else:
                print(f"\n[FAIL] Could not load c_golden.txt or c.txt")
        else:
            # matrix_C_golden.txt: row-major matrix. c.txt may be word layout; reshape to (GEMM_SIZE_A, GEMM_SIZE_B)
            if golden_matrix is not None and output_matrix is not None:
                try:
                    with open(config_file_path, 'r') as f:
                        cfg = json.load(f)
                    gemm_a = int(cfg.get('GEMM_SIZE_A', 32))
                    gemm_b = int(cfg.get('GEMM_SIZE_B', 64))
                except Exception:
                    gemm_a, gemm_b = 32, 64
                wrd_ln = get_word_length(data_type)
                expected_elements = gemm_a * gemm_b
                expected_words = expected_elements // wrd_ln
                if output_matrix.ndim == 2 and output_matrix.shape[1] == wrd_ln and output_matrix.shape[0] * wrd_ln == expected_elements:
                    output_matrix = output_matrix.reshape(gemm_a, gemm_b)
                    print(f"  Reshaped c.txt from word layout ({expected_words} lines x {wrd_ln} elems) to matrix ({gemm_a}x{gemm_b})")

            if golden_matrix is not None and output_matrix is not None:
                result = compare_matrices(golden_matrix, output_matrix, "Matrix C (c.txt vs matrix_C_golden.txt)")
                if result:
                    print(f"\n[OK] c.txt matches matrix_C_golden.txt")
                else:
                    print(f"\n[FAIL] c.txt does not match matrix_C_golden.txt")
                    try:
                        g0 = golden_matrix[0, :min(8, golden_matrix.shape[1])]
                        o0 = output_matrix[0, :min(8, output_matrix.shape[1])]
                        print(f"\n  Golden row 0 (first 8): {g0.tolist()}")
                        print(f"  Output row 0 (first 8):  {o0.tolist()}")
                    except Exception:
                        pass
                    for name, fn in [("matrix_A_input.txt", "matrix_A_input.txt"), ("b_golden.txt", "b_golden.txt")]:
                        p = os.path.join(directory, fn)
                        if os.path.isfile(p):
                            try:
                                with open(p, "r") as f:
                                    first = f.readline().strip()[:80]
                                print(f"  Expected first line of {name}: {first}...")
                            except Exception:
                                pass
                    print(f"\n  Verify the run used these inputs: check the host app log for 'A first word' and 'B first word'")
            else:
                print(f"\n[FAIL] Could not load matrix_C_golden.txt or c.txt")
                print(f"  To confirm a0_casc matches DMA order: python3 verify_io_consistency.py {os.path.basename(directory)}")
        return result
    else:
        if not os.path.exists(golden_path):
            print(f"  [FAIL] Golden file not found: {golden_path}")
        if not os.path.exists(generated_output_path):
            print(f"  [FAIL] Output file not found: {generated_output_path}")
        return False

def main():
    """
    Main function for AI Engine GEMM output comparison.
    
    This function orchestrates the complete comparison workflow:
    1. Reads configuration from config.json
    2. Calculates derived parameters
    3. Displays configuration summary
    4. Determines file locations
    5. Executes comparison process
    6. Returns appropriate exit code
    
    Configuration Source:
        - Reads from design/design_configs/config.json
        - Provides default values for all parameters
        - Handles missing or invalid configuration gracefully
        
    Derived Parameters:
        - WRD_LN: Word length based on data type
        - GRAPH_ITER_CNT: Graph iteration count calculation
        - Directory names: Based on GEMM_SIZE_A, GEMM_SIZE_AB, GEMM_SIZE_B
        
    File Discovery:
        - Golden file: gemm_{SIZE}_ioFiles/matrix_C_golden.txt
        - Output file: c.txt
        
    Returns:
        int: Exit code (0 for success, 1 for failure)
    """
    # Read all parameters from config file
    script_dir = os.path.dirname(os.path.abspath(__file__))
    config_file = os.path.join(script_dir, '..', '..', 'design_configs', 'config.json')
    
    print(f"Reading configuration from: {config_file}")
    params = read_all_parameters_from_config(config_file)
    
    # Extract parameters
    # GEMM_SIZE_A, GEMM_SIZE_AB, GEMM_SIZE_B are REQUIRED - must be explicitly provided
    if 'GEMM_SIZE_A' not in params:
        raise ValueError("GEMM_SIZE_A is required in config.json. Please provide GEMM_SIZE_A, GEMM_SIZE_AB, and GEMM_SIZE_B.")
    if 'GEMM_SIZE_AB' not in params:
        raise ValueError("GEMM_SIZE_AB is required in config.json. Please provide GEMM_SIZE_A, GEMM_SIZE_AB, and GEMM_SIZE_B.")
    if 'GEMM_SIZE_B' not in params:
        raise ValueError("GEMM_SIZE_B is required in config.json. Please provide GEMM_SIZE_A, GEMM_SIZE_AB, and GEMM_SIZE_B.")
    GEMM_SIZE_A = params['GEMM_SIZE_A']
    GEMM_SIZE_AB = params['GEMM_SIZE_AB']
    GEMM_SIZE_B = params['GEMM_SIZE_B']
    # Read new parameter names (with backward compatibility)
    SPLIT_A = params.get('SPLIT_A', params.get('SPLIT', 2))
    SPLIT_B = params.get('SPLIT_B', params.get('SPLIT', 2))
    CASC_LN_AB = params.get('CASC_LN_AB', params.get('CASC_LN', 8))
    
    # For backward compatibility, also set SPLIT and CASC_LN
    SPLIT = SPLIT_B  # Legacy: SPLIT refers to SPLIT_B for Matrix C
    CASC_LN = CASC_LN_AB  # Legacy: CASC_LN refers to CASC_LN_AB
    
    # Calculate DIM_A, DIM_B as min(DIM, ...); DIM_AB is always GEMM_SIZE_AB // CASC_LN_AB
    DIM = params.get('DIM', 16)
    DIM_A = params.get('DIM_A', min(DIM, GEMM_SIZE_A // max(1, SPLIT_A)))
    DIM_AB = params.get('DIM_AB', GEMM_SIZE_AB // max(1, CASC_LN_AB))
    DIM_B = params.get('DIM_B', min(DIM, GEMM_SIZE_B // max(1, SPLIT_B)))
    DATA_TYPE = params['DATA_TYPE']
    TARGET_HW_EMU = params['TARGET_HW_EMU']
    ITER_CNT = params['ITER_CNT']
    N_SAMPLES = params['N_SAMPLES']
    GEMM_INSTS = params['GEMM_INSTS']
    EN_TRACE = params['EN_TRACE']
    
    # Calculate derived parameters
    WRD_LN = get_word_length(DATA_TYPE)
    # Formula: GRAPH_ITER_CNT = (GEMM_SIZE_A × (GEMM_SIZE_B / SPLIT_B)) / (DIM_A × DIM_B)
    # Each output file contains: GEMM_SIZE_A rows × (GEMM_SIZE_B / SPLIT_B) columns
    # Each iteration produces: DIM_A × DIM_B elements per file
    GRAPH_ITER_CNT = (GEMM_SIZE_A * GEMM_SIZE_B // SPLIT_B) // (DIM_A * DIM_B)
    
    print(f"\nConfiguration Summary:")
    print(f"GEMM_SIZE_A: {GEMM_SIZE_A}, GEMM_SIZE_AB: {GEMM_SIZE_AB}, GEMM_SIZE_B: {GEMM_SIZE_B}")
    print(f"DIM_A: {DIM_A} (min({DIM}, {GEMM_SIZE_A}/{SPLIT_A})), DIM_AB: {DIM_AB} ({GEMM_SIZE_AB}//{CASC_LN_AB}), DIM_B: {DIM_B} (min({DIM}, {GEMM_SIZE_B}/{SPLIT_B}))")
    print(f"SPLIT_A: {SPLIT_A}, SPLIT_B: {SPLIT_B}")
    print(f"CASC_LN_AB: {CASC_LN_AB}")
    print(f"GRAPH_ITER_CNT: {GRAPH_ITER_CNT} (computed: ({GEMM_SIZE_A}×{GEMM_SIZE_B}/{SPLIT_B})/({DIM_A}×{DIM_B}))")
    print(f"Data Type: {DATA_TYPE}")
    print(f"Word Length (WRD_LN): {WRD_LN} elements per 128-bit PLIO")
    print(f"Target HW EMU: {TARGET_HW_EMU}")
    print(f"Iteration Count: {ITER_CNT}")
    print(f"N Samples: {N_SAMPLES}")
    print(f"GEMM Instances: {GEMM_INSTS}")
    print(f"Enable Trace: {EN_TRACE}")
    
    # Calculate the directory name based on GEMM size
    script_dir = os.path.dirname(os.path.abspath(__file__))
    gemm_dir_name = f"gemm_{GEMM_SIZE_A}x{GEMM_SIZE_AB}x{GEMM_SIZE_B}_ioFiles"
    gemm_dir_path = os.path.join(script_dir, gemm_dir_name)
    
    # If directory doesn't exist in script directory, try current directory
    if not os.path.exists(gemm_dir_path):
        gemm_dir_path = gemm_dir_name
    
    print(f"\nMatrix parameters:")
    print(f"GEMM_SIZE_A: {GEMM_SIZE_A}, GEMM_SIZE_AB: {GEMM_SIZE_AB}, GEMM_SIZE_B: {GEMM_SIZE_B}")
    print(f"SPLIT: {SPLIT}, CASC_LN: {CASC_LN}")
    print(f"Tile dimensions: DIM_A={DIM_A}, DIM_AB={DIM_AB}, DIM_B={DIM_B}")
    print(f"Looking for golden files in: {gemm_dir_name}")
    # Determine simulator output path for display
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(script_dir, '..', '..', '..'))
    build_base = os.path.join(project_root, 'build')
    config_file_path = os.path.join(project_root, 'design', 'design_configs', 'config.json')
    target = 'hw'
    if os.path.exists(config_file_path):
        try:
            with open(config_file_path, 'r') as f:
                config_data = json.load(f)
                if 'TARGET' in config_data:
                    target = str(config_data['TARGET']).lower()
        except Exception:
            pass
    dir_name = os.path.basename(gemm_dir_path)
    if dir_name.startswith('gemm_') and dir_name.endswith('_ioFiles'):
        size_part = dir_name[5:-8]
        simulator_dir = os.path.join(build_base, f'gemm_{size_part}', 'x1', target, 'aiesimulator_output', 'data')
    else:
        simulator_dir = os.path.join(build_base, 'gemm_32x32x32', 'x1', target, 'aiesimulator_output', 'data')
    print(f"Looking for output files in: {simulator_dir} (or current directory)")
    
    # Run the comparison (use max of A, AB, B for directory naming)
    max_gemm_size = max(GEMM_SIZE_A, GEMM_SIZE_AB, GEMM_SIZE_B)
    success = run_comparison(gemm_dir_path, DATA_TYPE, max_gemm_size)
    
    return 0 if success else 1

if __name__ == "__main__":
    sys.exit(main())
