#!/usr/bin/env python3
"""
AI Engine GEMM Output Comparison Script
======================================

This script provides comprehensive comparison functionality between AI Engine GEMM
simulator output and golden reference files. It supports all data types, matrix
dimensions, and configuration parameters used in the AI Engine GEMM application.

Key Features:
- Automatic configuration reading from config.json
- Support for all data types (int16, int32, float, bfloat16, int8, int4)
- Tolerance-based comparison for floating-point data
- Exact comparison for integer data types
- Consolidated and individual split file comparison
- Detailed difference reporting with statistics
- Comprehensive error handling and validation

Architecture:
- Configuration Management: Reads all parameters from centralized config.json
- Matrix Loading: Handles different data types with appropriate numpy dtypes
- Comparison Engine: Implements tolerance-based and exact comparison methods
- Reporting System: Provides detailed statistics and difference analysis

Usage:
    python compare_outputs.py

Prerequisites:
- config.json file in design/design_configs/ directory
- Golden reference files generated by plioGen.py
- Simulator output files (c.txt or individual split files)

Output Files Expected:
- c_golden.txt: Consolidated golden reference output
- c{i}_golden.txt: Individual split golden reference files
- c.txt: Generated simulator output (consolidated)
- c{i}.txt: Individual split simulator output files

Return Codes:
- 0: All comparisons passed successfully
- 1: One or more comparisons failed

Author: Advanced Micro Devices, Inc.
Copyright (C) 2024, Advanced Micro Devices, Inc. All rights reserved.
SPDX-License-Identifier: MIT
"""

import os
import sys
import numpy as np
import json

def read_all_parameters_from_config(config_file_path):
    """
    Read all parameters from config.json file.
    
    This function loads the centralized configuration file and extracts all
    necessary parameters for the AI Engine GEMM application. It provides
    default values for all parameters to ensure robust operation even if
    the configuration file is missing or incomplete.
    
    Args:
        config_file_path (str): Path to the config.json file
        
    Returns:
        dict: Dictionary containing all configuration parameters with the following keys:
            - GEMM_SIZE (int): Matrix dimension (default: 128)
            - DIM (int): Tile dimension (default: 8)
            - SPLIT (int): Number of AI Engine splits (default: 2)
            - CASC_LN (int): Number of cascade levels (default: 8)
            - DATA_TYPE (str): Data type (default: 'int16')
            - TARGET_HW_EMU (int): Hardware emulation target flag (default: 1)
            - ITER_CNT (int): Iteration count (default: -1)
            - N_SAMPLES (int): Number of samples (default: 1)
            - GEMM_INSTS (int): Number of GEMM instances (default: 1)
            - EN_TRACE (int): Enable tracing flag (default: 0)
    
    Raises:
        FileNotFoundError: If config file doesn't exist (handled gracefully)
        Exception: If JSON parsing fails (handled gracefully)
    """
    # Initialize default values
    params = {
        'GEMM_SIZE': 32,
        'DIM': 16,
        'SPLIT': 2,
        'CASC_LN': 8,
        'DATA_TYPE': 'int16',
        'TARGET_HW_EMU': 0,
        'ITER_CNT': 1,
        'N_SAMPLES': 1,
        'GEMM_INSTS': 1,
        'EN_TRACE': 0,
        'TILE_MEM_BYTES': 32768,
        'PL_FREQ': 312.5,
        'ENABLE_ML_BENCHMARKS': 0,
        'TARGET': 'hw'
    }
    
    try:
        with open(config_file_path, 'r') as f:
            config_data = json.load(f)
        
        # Map JSON keys to our parameter names (only user-specified parameters)
        if 'GEMM_SIZE' in config_data:
            params['GEMM_SIZE'] = int(config_data['GEMM_SIZE'])
        if 'DIM' in config_data:
            params['DIM'] = int(config_data['DIM'])
        if 'SPLIT' in config_data:
            params['SPLIT'] = int(config_data['SPLIT'])
        if 'CASC_LN' in config_data:
            params['CASC_LN'] = int(config_data['CASC_LN'])
        if 'ITER_CNT' in config_data:
            params['ITER_CNT'] = int(config_data['ITER_CNT'])
        if 'N_SAMPLES' in config_data:
            params['N_SAMPLES'] = int(config_data['N_SAMPLES'])
        if 'GEMM_INSTS' in config_data:
            params['GEMM_INSTS'] = int(config_data['GEMM_INSTS'])
        if 'EN_TRACE' in config_data:
            params['EN_TRACE'] = int(config_data['EN_TRACE'])
        if 'DATA_TYPE' in config_data:
            params['DATA_TYPE'] = str(config_data['DATA_TYPE'])
        
        # Set TARGET and TARGET_HW_EMU based on TARGET field
        if 'TARGET' in config_data:
            params['TARGET'] = config_data['TARGET']
            target = str(config_data['TARGET']).lower()
            if target == 'hw_emu':
                params['TARGET_HW_EMU'] = 1
            else:
                params['TARGET_HW_EMU'] = 0
        
        # Set additional parameters from config
        if 'TILE_MEM_BYTES' in config_data:
            params['TILE_MEM_BYTES'] = int(config_data['TILE_MEM_BYTES'])
        if 'PL_FREQ' in config_data:
            params['PL_FREQ'] = float(config_data['PL_FREQ'])
        if 'ENABLE_ML_BENCHMARKS' in config_data:
            params['ENABLE_ML_BENCHMARKS'] = int(config_data['ENABLE_ML_BENCHMARKS'])

        print(f"Successfully read parameters from config file:")
        for key, value in params.items():
            print(f"  {key}: {value}")
        
        return params
        
    except FileNotFoundError:
        print(f"Warning: Config file not found: {config_file_path}, using defaults")
        return params
    except Exception as e:
        print(f"Error reading config file: {e}, using defaults")
        return params

def get_word_length(data_type="int16"):
    """
    Calculate the word length (WRD_LN) based on data type.
    
    Word length represents the number of data elements that fit in a 128-bit PLIO transfer.
    This is crucial for understanding how data is packed and transferred between the
    Programmable Logic and AI Engine via PLIO interfaces.
    
    Args:
        data_type (str): Data type string (e.g., 'int16', 'int32', 'float', 'bfloat16')
        
    Returns:
        int: Number of elements that fit in a 128-bit transfer
        
    Supported Data Types:
        - int4/uint4: 32 elements per 128-bit transfer (4 bits per element)
        - int8/uint8: 16 elements per 128-bit transfer (8 bits per element)
        - int16/uint16/bfloat16: 8 elements per 128-bit transfer (16 bits per element)
        - int32/uint32/float: 4 elements per 128-bit transfer (32 bits per element)
        - Default: 8 elements per 128-bit transfer (for unsupported types)
    """
    if data_type in ["int4", "uint4"]:
        return 32
    elif data_type in ["int8", "uint8"]:
        return 16
    elif data_type in ["int16", "uint16", "bfloat16"]:
        return 8
    else:
        return 8


def load_matrix_from_file(filepath, data_type="int16"):
    """
    Load matrix from file with appropriate data type handling.
    
    This function loads matrix data from text files and converts it to the
    appropriate numpy data type based on the specified data type. It handles
    all supported data types used in the AI Engine GEMM application.
    
    Args:
        filepath (str): Path to the matrix file
        data_type (str): Data type string (e.g., 'int16', 'int32', 'float', 'bfloat16')
        
    Returns:
        numpy.ndarray or None: Loaded matrix with appropriate data type, or None if loading fails
        
    Supported Data Types:
        - bfloat16: Loaded as float32 (numpy doesn't have native bfloat16)
        - float: Loaded as float32
        - int16/uint16: Loaded as int16
        - int32/uint32: Loaded as int32
        - int8/uint8: Loaded as int8
        - int4/uint4: Loaded as int8 (int4 stored as int8)
        - Default: int16 (for backward compatibility)
        
    Raises:
        Exception: If file loading fails (handled gracefully, returns None)
    """
    try:
        if data_type == "bfloat16":
            matrix = np.loadtxt(filepath, dtype=np.float32)
        elif data_type == "float":
            matrix = np.loadtxt(filepath, dtype=np.float32)
        elif data_type in ["int16", "uint16"]:
            matrix = np.loadtxt(filepath, dtype=np.int16)
        elif data_type in ["int32", "uint32"]:
            matrix = np.loadtxt(filepath, dtype=np.int32)
        elif data_type in ["int8", "uint8"]:
            matrix = np.loadtxt(filepath, dtype=np.int8)
        elif data_type in ["int4", "uint4"]:
            matrix = np.loadtxt(filepath, dtype=np.int8)  # int4 stored as int8
        else:
            # Default to int16 for backward compatibility
            matrix = np.loadtxt(filepath, dtype=np.int16)
        return matrix
    except Exception as e:
        print(f"Error loading matrix from {filepath}: {e}")
        return None

def compare_matrices(golden_matrix, output_matrix, matrix_name):
    """
    Compare two matrices and report differences with tolerance for float precision.
    
    This function performs intelligent comparison between golden reference and
    generated output matrices. It uses different comparison strategies based on
    the data type: exact comparison for integer types and tolerance-based
    comparison for floating-point types.
    
    Args:
        golden_matrix (numpy.ndarray): Golden reference matrix
        output_matrix (numpy.ndarray): Generated output matrix
        matrix_name (str): Name of the matrix for reporting purposes
        
    Returns:
        bool: True if matrices match (within tolerance), False otherwise
        
    Comparison Strategy:
        - Integer types (int8, int16, int32, uint8, uint16, uint32, int4, uint4):
          Exact comparison with zero tolerance
        - Floating-point types (float, bfloat16):
          Tolerance-based comparison with 1e-4 absolute tolerance
          Data is rounded to 4 decimal places before comparison
          
    Reporting Features:
        - Shape validation and mismatch reporting
        - Detailed statistics (max diff, mean diff, match percentage)
        - First 10 differences shown with positions and values
        - Comprehensive error reporting for debugging
    """
    if golden_matrix.shape != output_matrix.shape:
        print(f"Shape mismatch for {matrix_name}:")
        print(f"  Golden shape: {golden_matrix.shape}")
        print(f"  Output shape: {output_matrix.shape}")
        return False
    
    # Use tolerance-based comparison for float data
    if golden_matrix.dtype in [np.float32, np.float64]:
        # Round to 0 decimal places for comparison (whole numbers only)
        golden_rounded = np.round(golden_matrix, 0)
        output_rounded = np.round(output_matrix, 0)
        
        # Use numpy's allclose with tolerance
        tolerance = 1e0  # 1.0
        is_close = np.allclose(golden_rounded, output_rounded, atol=tolerance, rtol=0)
        
        if is_close:
            print(f"[OK] {matrix_name}: Match within tolerance (whole numbers only, ignoring all decimal digits)")
            return True
        else:
            # Calculate differences on rounded data
            diff_matrix = np.abs(golden_rounded - output_rounded)
            max_diff = np.max(diff_matrix)
            mean_diff = np.mean(diff_matrix)
            num_differences = np.count_nonzero(diff_matrix)
            total_elements = golden_matrix.size
            match_percentage = ((total_elements - num_differences) / total_elements) * 100
            
            print(f"[FAIL] {matrix_name}: Found {num_differences} differences after rounding to whole numbers")
            print(f"  Maximum absolute difference: {max_diff}")
            print(f"  Mean absolute difference: {mean_diff:.4f}")
            print(f"  Percentage of matching elements: {match_percentage:.2f}%")
            
            # Show first few differences
            diff_positions = np.where(diff_matrix > 0)
            num_to_show = min(10, num_differences)
            
            print(f"  First {num_to_show} differences:")
            for i in range(num_to_show):
                row, col = diff_positions[0][i], diff_positions[1][i]
                golden_val = golden_matrix[row, col]
                output_val = output_matrix[row, col]
                golden_rounded_val = golden_rounded[row, col]
                output_rounded_val = output_rounded[row, col]
                print(f"    Position [{row:3d},{col:3d}]: Golden={golden_val:.4f} -> {golden_rounded_val:.1f}, Output={output_val:.4f} -> {output_rounded_val:.1f}, Diff={diff_matrix[row, col]:.1f}")
    else:
        # Exact comparison for integer data
        diff_matrix = np.abs(golden_matrix - output_matrix)
        max_diff = np.max(diff_matrix)
        mean_diff = np.mean(diff_matrix)
        num_differences = np.count_nonzero(diff_matrix)
        total_elements = golden_matrix.size
        match_percentage = ((total_elements - num_differences) / total_elements) * 100
        
        if num_differences == 0:
            print(f"[OK] {matrix_name}: Perfect match (100% identical)")
            return True
        else:
            print(f"[FAIL] {matrix_name}: Found {num_differences} differences")
            print(f"  Maximum absolute difference: {max_diff}")
            print(f"  Mean absolute difference: {mean_diff:.4f}")
            print(f"  Percentage of matching elements: {match_percentage:.2f}%")
        
        # Show first few differences
        diff_positions = np.where(diff_matrix > 0)
        num_to_show = min(10, num_differences)
        
        print(f"  First {num_to_show} differences:")
        for i in range(num_to_show):
            row, col = diff_positions[0][i], diff_positions[1][i]
            golden_val = golden_matrix[row, col]
            output_val = output_matrix[row, col]
            print(f"    [{row}, {col}]: Golden={golden_val}, Output={output_val}")
        
        if num_differences > 10:
            print(f"  ... and {num_differences - 10} more differences")
        
        return False

def run_comparison(directory, split_b=2, data_type="int16"):
    """
    Run comparison between golden files and generated output.
    
    This function orchestrates the complete comparison process between golden
    reference files and generated simulator output. It supports both consolidated
    and individual split file comparison strategies.
    
    Args:
        directory (str): Directory containing golden reference files
        split_b (int): Number of splits for individual file comparison (default: 2)
        data_type (str): Data type for matrix loading (default: "int16")
        
    Returns:
        bool: True if all comparisons pass, False otherwise
        
    Comparison Strategy:
        1. Primary: Consolidated comparison (c_golden.txt vs c.txt)
           - Loads consolidated golden reference file
           - Compares with generated consolidated output
           - Returns immediately if successful
           
        2. Fallback: Individual split comparison
           - Compares each split individually (c{i}_golden.txt vs c{i}.txt)
           - Looks for simulator output in ../build/x86sim/x86simulator_output/data/
           - Reports results for each split
           
    File Locations:
        - Golden files: {directory}/c_golden.txt, {directory}/c{i}_golden.txt
        - Generated output: c.txt (consolidated), c{i}.txt (individual splits)
        - Simulator output: ../build/x86sim/x86simulator_output/data/c{i}.txt
        
    Error Handling:
        - Graceful handling of missing files
        - Detailed error reporting for debugging
        - Continues comparison even if some files are missing
    """
    print(f"\nStarting comparison in directory: {directory}")
    print(f"Data type: {data_type}")
    
    # Look for generated output file (c.txt) in the current directory
    generated_output_path = "c.txt"
    
    all_match = True
    
    # First, try to compare the consolidated c_golden.txt with c.txt
    consolidated_golden_path = os.path.join(directory, "c_golden.txt")
    
    if os.path.exists(consolidated_golden_path) and os.path.exists(generated_output_path):
        print(f"\nComparing consolidated output:")
        print(f"  Golden: {consolidated_golden_path}")
        print(f"  Generated: {generated_output_path}")
        
        # Load matrices
        golden_matrix = load_matrix_from_file(consolidated_golden_path, data_type)
        output_matrix = load_matrix_from_file(generated_output_path, data_type)
        
        if golden_matrix is not None and output_matrix is not None:
            if compare_matrices(golden_matrix, output_matrix, "Consolidated C"):
                print(f"\n[OK] Consolidated comparison passed: Generated output matches golden file")
                return True
            else:
                all_match = False
        else:
            all_match = False
    else:
        print(f"[FAIL] Consolidated golden file not found: {consolidated_golden_path}")
        print(f"[FAIL] Generated output file not found: {generated_output_path}")
        all_match = False
    
    # If consolidated comparison fails or files don't exist, try individual split files
    if not all_match:
        print(f"\nTrying individual split file comparison...")
        
        # Look for simulator output files (fallback)
        simulator_dir = "../build/x86sim/x86simulator_output/data"
        
        # Compare each matrix
        for i in range(split_b):
            golden_path = os.path.join(directory, f"c{i}_golden.txt")
            output_path = os.path.join(simulator_dir, f"c{i}.txt")
            
            if not os.path.exists(golden_path):
                print(f"[FAIL] Golden file not found: {golden_path}")
                all_match = False
                continue
                
            if not os.path.exists(output_path):
                print(f"[FAIL] Simulator output not found: {output_path}")
                all_match = False
                continue
            
            print(f"\nComparing C{i}:")
            print(f"  Golden: {golden_path}")
            print(f"  Output: {output_path}")
            
            # Load matrices
            golden_matrix = load_matrix_from_file(golden_path, data_type)
            output_matrix = load_matrix_from_file(output_path, data_type)
            
            if golden_matrix is None or output_matrix is None:
                all_match = False
                continue
                
            # Compare the matrices
            if not compare_matrices(golden_matrix, output_matrix, f"C{i}"):
                all_match = False
    
    # Summary
    if all_match:
        print(f"\n[OK] All comparisons passed: All output files match their golden files")
    else:
        print(f"\n[FAIL] Some comparisons failed: Check the differences above")
    
    return all_match

def main():
    """
    Main function for AI Engine GEMM output comparison.
    
    This function orchestrates the complete comparison workflow:
    1. Reads configuration from config.json
    2. Calculates derived parameters
    3. Displays configuration summary
    4. Determines file locations
    5. Executes comparison process
    6. Returns appropriate exit code
    
    Configuration Source:
        - Reads from design/design_configs/config.json
        - Provides default values for all parameters
        - Handles missing or invalid configuration gracefully
        
    Derived Parameters:
        - WRD_LN: Word length based on data type
        - GRAPH_ITER_CNT: Graph iteration count calculation
        - Directory names: Based on GEMM_SIZE
        
    File Discovery:
        - Golden files: gemm_{SIZE}x{SIZE}x{SIZE}_ioFiles/
        - Output files: c.txt (consolidated), c{i}.txt (individual)
        
    Returns:
        int: Exit code (0 for success, 1 for failure)
    """
    # Read all parameters from config file
    script_dir = os.path.dirname(os.path.abspath(__file__))
    config_file = os.path.join(script_dir, '..', '..', 'design_configs', 'config.json')
    
    print(f"Reading configuration from: {config_file}")
    params = read_all_parameters_from_config(config_file)
    
    # Extract parameters
    GEMM_SIZE = params['GEMM_SIZE']
    DIM = params['DIM']
    SPLIT = params['SPLIT']
    CASC_LN = params['CASC_LN']
    DATA_TYPE = params['DATA_TYPE']
    TARGET_HW_EMU = params['TARGET_HW_EMU']
    ITER_CNT = params['ITER_CNT']
    N_SAMPLES = params['N_SAMPLES']
    GEMM_INSTS = params['GEMM_INSTS']
    EN_TRACE = params['EN_TRACE']
    
    # Calculate derived parameters
    WRD_LN = get_word_length(DATA_TYPE)
    GRAPH_ITER_CNT = (GEMM_SIZE * GEMM_SIZE) // (DIM * DIM) // SPLIT
    
    print(f"\nConfiguration Summary:")
    print(f"GEMM_SIZE: {GEMM_SIZE}")
    print(f"DIM: {DIM}")
    print(f"SPLIT: {SPLIT}")
    print(f"CASC_LN: {CASC_LN}")
    print(f"GRAPH_ITER_CNT: {GRAPH_ITER_CNT} (computed: ({GEMM_SIZE}×{GEMM_SIZE})/({DIM}×{DIM})/{SPLIT})")
    print(f"Data Type: {DATA_TYPE}")
    print(f"Word Length (WRD_LN): {WRD_LN} elements per 128-bit PLIO")
    print(f"Target HW EMU: {TARGET_HW_EMU}")
    print(f"Iteration Count: {ITER_CNT}")
    print(f"N Samples: {N_SAMPLES}")
    print(f"GEMM Instances: {GEMM_INSTS}")
    print(f"Enable Trace: {EN_TRACE}")
    
    # Calculate the directory name based on GEMM size
    gemm_dir_name = f"gemm_{GEMM_SIZE}x{GEMM_SIZE}x{GEMM_SIZE}_ioFiles"
    
    print(f"\nMatrix parameters:")
    print(f"GEMM_SIZE: {GEMM_SIZE}")
    print(f"SPLIT: {SPLIT}, CASC_LN: {CASC_LN}")
    print(f"Tile dimension: DIM={DIM}")
    print(f"Looking for golden files in: {gemm_dir_name}")
    print(f"Looking for output files in: c.txt")
    
    # Run the comparison
    success = run_comparison(gemm_dir_name, SPLIT, DATA_TYPE)
    
    return 0 if success else 1

if __name__ == "__main__":
    sys.exit(main())
