/********************************************* Disclaimer *********************************************/
/* This file is generated by aiecompiler . */
/* Changes to this file may cause incorrect behavior and will be lost if aiecompiler is invoked again.*/

#include <iostream>
#include "adf/adf_api/AIEControlConfig.h"
#include "/home/mgrailoo/Vitis_Libraries/dsp/L1/include/aie/matrix_mult.hpp"


/************************** Graph Configurations  *****************************/

  adf::GraphConfig GraphConfigurations[] = {
  //{id, name, graphLoadElfFunc, graphInitFunc, graphDebugHalt, coreColumns, coreRows, iterMemColumns, iterMemRows, iterMemAddrs, triggered, plKernelInstanceNames, plAxiLiteModes, plDriverStartFuncs, plDriverCheckIPDoneFuncs}
    {0, "g", nullptr, nullptr, nullptr, {1, 2, 3, 4, 5, 6, 7, 7, 9, 10, 11, 12, 13, 14, 15, 16}, {1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 1, 3, 4, 5, 5, 7, 7, 8, 10, 10, 12, 12, 13, 15, 15}, {1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0}, {0x3b64, 0x4004, 0x4, 0x41c4, 0x4, 0x4, 0x4004, 0x3b64, 0x41c4, 0x41c4, 0x41c4, 0x4, 0x4004, 0x4, 0x3b64, 0x4004}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {}, {}, {}, {},  }, 
  };
  const int NUM_GRAPH = 1;

/************************** PLIO Configurations  *****************************/

  adf::PLIOConfig PLIOConfigurations[] = {
  //{id, name, loginal_name, shim_column, slaveOrMaster, streamId}
    {0, "g.matA_inp[0]", "DataInA0_CASC0", 9, 0, 0},
    {1, "g.matA_inp[1]", "DataInA0_CASC1", 10, 0, 4},
    {2, "g.matA_inp[2]", "DataInA0_CASC2", 11, 0, 4},
    {3, "g.matA_inp[3]", "DataInA0_CASC3", 12, 0, 4},
    {4, "g.matA_inp[4]", "DataInA0_CASC4", 13, 0, 4},
    {5, "g.matA_inp[5]", "DataInA0_CASC5", 14, 0, 4},
    {6, "g.matA_inp[6]", "DataInA0_CASC6", 15, 0, 0},
    {7, "g.matA_inp[7]", "DataInA0_CASC7", 16, 0, 4},
    {8, "g.matB_inp[0]", "DataInB0_CASC0", 6, 0, 0},
    {9, "g.matB_inp[1]", "DataInB0_CASC1", 8, 0, 0},
    {10, "g.matB_inp[2]", "DataInB0_CASC2", 6, 0, 4},
    {11, "g.matB_inp[3]", "DataInB0_CASC3", 5, 0, 4},
    {12, "g.matB_inp[4]", "DataInB0_CASC4", 5, 0, 0},
    {13, "g.matB_inp[5]", "DataInB0_CASC5", 7, 0, 4},
    {14, "g.matB_inp[6]", "DataInB0_CASC6", 8, 0, 4},
    {15, "g.matB_inp[7]", "DataInB0_CASC7", 7, 0, 0},
    {16, "g.matC_out[0]", "DataOutC0", 7, 1, 0},
    {17, "g.matB_inp[8]", "DataInB1_CASC0", 9, 0, 4},
    {18, "g.matB_inp[9]", "DataInB1_CASC1", 10, 0, 0},
    {19, "g.matB_inp[10]", "DataInB1_CASC2", 11, 0, 0},
    {20, "g.matB_inp[11]", "DataInB1_CASC3", 12, 0, 0},
    {21, "g.matB_inp[12]", "DataInB1_CASC4", 13, 0, 0},
    {22, "g.matB_inp[13]", "DataInB1_CASC5", 14, 0, 0},
    {23, "g.matB_inp[14]", "DataInB1_CASC6", 15, 0, 4},
    {24, "g.matB_inp[15]", "DataInB1_CASC7", 16, 0, 0},
    {25, "g.matC_out[1]", "DataOutC1", 16, 1, 0},
  };
  const int NUM_PLIO = 26;


/************************** ADF API initializer *****************************/

  class InitializeAIEControlXRT
  {
  public:
    InitializeAIEControlXRT()
    {
      std::cout<<"Initializing ADF API..."<<std::endl;
#ifdef __EXCLUDE_PL_CONTROL__
      bool exclude_pl_control = true;
#else
      bool exclude_pl_control = false;
#endif
      adf::initializeConfigurations(nullptr, 0, 0, 0,
                                    GraphConfigurations, NUM_GRAPH,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    PLIOConfigurations, NUM_PLIO,
                                    nullptr, 0, 0, nullptr,
                                    false, exclude_pl_control, false, nullptr,
                                    true, 2);

    }
  } initAIEControlXRT;



#if !defined(__CDO__) && !defined(__AIECONTROLCODE__) && !defined(__TXN_BIN__)

  using namespace adf;

// Kernel Stub Definition
template<> void xf::dsp::aie::blas::matrix_mult::matrix_mult<short, short, 16, 4, 16, 0, 0, 1, 0, 0, 0, 64, 64, false, true, 16, 4, 16, 0, 1>::matMult(adf::io_buffer<short, adf::direction::in, adf::io_buffer_config<>> &__restrict,adf::io_buffer<short, adf::direction::in, adf::io_buffer_config<>> &__restrict,output_stream<acc48> *) { /* Stub */ } 
template<> void xf::dsp::aie::blas::matrix_mult::matrix_mult<short, short, 16, 4, 16, 0, 0, 1, 0, 0, 0, 64, 64, true, false, 16, 4, 16, 0, 1>::matMult(adf::io_buffer<short, adf::direction::in, adf::io_buffer_config<>> &__restrict,adf::io_buffer<short, adf::direction::in, adf::io_buffer_config<>> &__restrict,input_stream<acc48> *,adf::io_buffer<short, adf::direction::out, adf::io_buffer_config<>> &__restrict) { /* Stub */ } 
template<> void xf::dsp::aie::blas::matrix_mult::matrix_mult<short, short, 16, 4, 16, 0, 0, 1, 0, 0, 0, 64, 64, true, true, 16, 4, 16, 0, 1>::matMult(adf::io_buffer<short, adf::direction::in, adf::io_buffer_config<>> &__restrict,adf::io_buffer<short, adf::direction::in, adf::io_buffer_config<>> &__restrict,input_stream<acc48> *,output_stream<acc48> *) { /* Stub */ } 
#endif
